### ISSUE TITLE
Slack Api failing on Project Show when fetching slack users

### ISSUE THREAD

**Issue by gleenn** [CoMakery/comakery-app#48]
Not sure what's going bang

2016-03-08T17:08:31.919759+00:00 app[web.1]: Started GET "/projects/1" for 157.130.196.214 at 2016-03-08 17:08:31 +0000
2016-03-08T17:08:31.989391+00:00 app[web.1]: Processing by ProjectsController#show as HTML
2016-03-08T17:08:31.989520+00:00 app[web.1]:   Parameters: {"id"=>"1"}
2016-03-08T17:08:32.409690+00:00 app[web.1]: 
2016-03-08T17:08:32.409711+00:00 app[web.1]: Slack::Web::Api::Error (invalid_form_data):
2016-03-08T17:08:32.275194+00:00 app[web.1]: 200
2016-03-08T17:08:32.408831+00:00 app[web.1]: ** [Airbrake] Success: Net::HTTPOK
2016-03-08T17:08:32.409715+00:00 app[web.1]: 
2016-03-08T17:08:32.409712+00:00 app[web.1]:   app/lib/swarmbot/slack.rb:45:in `get_users'
2016-03-08T17:08:32.409713+00:00 app[web.1]:   app/interactors/get_awardable_accounts.rb:9:in `call'
2016-03-08T17:08:32.409714+00:00 app[web.1]:   app/controllers/projects_controller.rb:53:in `show'
2016-03-08T17:08:32.409715+00:00 app[web.1]: 
2016-03-08T17:08:32.203863+00:00 app[web.1]: post https://slack.com/api/users.list
2016-03-08T17:08:32.276106+00:00 app[web.1]: Completed 500 Internal Server Error in 286ms (ActiveRecord: 22.2ms)
2016-03-08T17:08:32.405882+00:00 heroku[router]: at=info method=GET path="/projects/1" host=swarmbot-staging.herokuapp.com request_id=c0fd1cae-05a2-4827-9731-cef062444197 fwd="157.130.196.214" dyno=web.1 connect=1ms service=500ms status=500 bytes=1669
2016-03-08T17:08:32.688975+00:00 heroku[router]: sock=client at=warning code=H27 desc="Client Request Interrupted" method=GET path="/" host=swarmbot-staging.herokuapp.com request_id=86572e82-4008-4a96-9673-b759054cb71c fwd="157.130.196.214" dyno=web.1 connect=0ms service=56ms status=499 bytes=6004

**Comment by gleenn** [comment]
Ignoring this as I think it was actually a problem somewhere else and can't repro.

How much do we care about when the slack api is down? Anything yet or just kicking the can down the road until it's more of a problem?
